import uuid

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

load_dotenv()

from db import get_analytics, get_log, get_submission, init_db, insert_submission, mark_under_review
from signals import classify_with_llm, compute_stylometrics

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

init_db()


# ---------------------------------------------------------------------------
# Confidence scoring
# ---------------------------------------------------------------------------

def compute_confidence(llm_score: float, stylo_score: float) -> float:
    return round(0.6 * llm_score + 0.4 * stylo_score, 4)


def attribution_from_confidence(confidence: float) -> str:
    if confidence > 0.65:
        return "likely_ai"
    if confidence < 0.35:
        return "likely_human"
    return "uncertain"


# ---------------------------------------------------------------------------
# Transparency labels
# ---------------------------------------------------------------------------

def generate_label(attribution: str, confidence: float) -> str:
    pct = f"{confidence:.0%}"
    if attribution == "likely_ai":
        return (
            f"AI-Generated Content ({pct} confidence)\n\n"
            "Our system's analysis found strong indicators that this content was likely "
            "generated by an AI tool rather than written by the author. This label is "
            "shown transparently so readers can weigh the content accordingly.\n\n"
            "If you are the creator and believe this classification is wrong, you have "
            "the right to appeal. Appeals are reviewed by a human moderator."
        )
    if attribution == "likely_human":
        return (
            f"Human-Created Content ({pct} confidence)\n\n"
            "Our system's analysis found strong indicators that this content was written "
            "by a human author. Thank you for sharing original work.\n\n"
            "Note: No automated system is perfect. This label reflects our best "
            "assessment, not a guarantee."
        )
    return (
        f"Origin Unclear ({pct} confidence)\n\n"
        "Our system could not confidently determine whether this content was written "
        "by a human or generated by an AI tool. It may contain a mix of both, or "
        "it may fall outside the patterns our system was trained to recognize.\n\n"
        "This content is published as-is. If you are the creator, you may submit "
        "a statement of origin to clarify the record."
    )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    body = request.get_json(silent=True)
    if not body:
        return jsonify({"error": "Request body must be JSON"}), 400

    text = body.get("text", "").strip()
    creator_id = body.get("creator_id", "").strip()

    if not text:
        return jsonify({"error": "Field 'text' is required and must be non-empty"}), 400
    if not creator_id:
        return jsonify({"error": "Field 'creator_id' is required and must be non-empty"}), 400

    content_id = str(uuid.uuid4())

    llm_score = classify_with_llm(text)
    stylo_score = compute_stylometrics(text)
    confidence = compute_confidence(llm_score, stylo_score)
    attribution = attribution_from_confidence(confidence)
    label = generate_label(attribution, confidence)

    insert_submission(
        content_id=content_id,
        creator_id=creator_id,
        text=text,
        attribution=attribution,
        confidence=confidence,
        llm_score=llm_score,
        stylo_score=stylo_score,
    )

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    body = request.get_json(silent=True)
    if not body:
        return jsonify({"error": "Request body must be JSON"}), 400

    content_id = body.get("content_id", "").strip()
    creator_reasoning = body.get("creator_reasoning", "").strip()

    if not content_id:
        return jsonify({"error": "Field 'content_id' is required"}), 400
    if not creator_reasoning:
        return jsonify({"error": "Field 'creator_reasoning' is required"}), 400

    submission = get_submission(content_id)
    if not submission:
        return jsonify({"error": f"No submission found for content_id '{content_id}'"}), 404

    mark_under_review(content_id, creator_reasoning)

    return jsonify({
        "message": "Appeal received and is under review",
        "content_id": content_id,
        "status": "under_review",
    })


@app.route("/log", methods=["GET"])
def log():
    try:
        limit = int(request.args.get("limit", 20))
    except ValueError:
        limit = 20
    entries = get_log(limit=limit)
    return jsonify({"entries": entries})


@app.route("/analytics", methods=["GET"])
def analytics():
    return jsonify(get_analytics())


if __name__ == "__main__":
    app.run(debug=True)
